apiVersion: v2
name: charts
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Frandom_2263464&psig=AOvVaw3lFZkFSBOU-wUf8ZpnY4gG&ust=1690861671584000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCNjA_eWEuIADFQAAAAAdAAAAABAD