---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: authdb
  labels:
    helm.sh/chart: charts-0.1.0
    helm.sh/release-name: {{ .Values.releasename }}
    helm.sh/release-namespace: {{ .Values.namespace }}
    app.kubernetes.io/name: authdb
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  members: 2
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: faraz
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongo-pass-auth
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: authneverlies
  statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: mongod
                readinessProbe:
                  failureThreshold: 40
                  initialDelaySeconds: 5
                  timeout: 30
                resources:
                  limits:
                    cpu: "0.2"
                    memory: 250M
                  requests:
                    cpu: "0.2"
                    memory: 200M
              - name: mongodb-agent
                readinessProbe:
                  failureThreshold: 40
                  initialDelaySeconds: 5
                  timeout: 30
                resources:
                  limits:
                    cpu: "0.2"
                    memory: 250M
                  requests:
                    cpu: "0.2"
                    memory: 200M
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required