apiVersion: v1
kind: Service
metadata:
  name: db-blog-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: blog-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017