apiVersion: v1
kind: Service
metadata:
  name: blogdb-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: blogdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017