apiVersion: v1
kind: Service
metadata:
  name: backend-mmi-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: backend-mmi
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100