apiVersion: v1
kind: Service
metadata:
  name: ui-mmi-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ui-mmi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001