apiVersion: v1
kind: Service
metadata:
  name: ui-mmi-service
spec:
  #type: NodePort
  type: LoadBalancer
  #externalName: faraz.com
  selector:
    app.kubernetes.io/name: ui-mmi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000