apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: mongo-pass-auth
stringData:
  password: {{ .Values.mongodb.authPassword }}

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: mongo-pass-blog
stringData:
  password: {{ .Values.mongodb.blogPassword }}

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: mongo-blog-uri
stringData:
  mongouri: mongodb://admin:{{ .Values.mongodb.blogPassword }}@blogdb-0.blogdb-svc.default.svc.cluster.local:27017,blogdb-1.blogdb-svc.default.svc.cluster.local:27017/?authSource=admin&replicaSet=myRepl&ssl=false

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: mongo-auth-uri
stringData:
  mongouri: mongodb://admin:{{ .Values.mongodb.authPassword }}@authdb-0.authdb-svc.default.svc.cluster.local:27017,authdb-1.authdb-svc.default.svc.cluster.local:27017/?authSource=admin&replicaSet=myRepl&ssl=false