from .analytics import (
    CREATE_USER_TABLE,
    CREATE_USER_SESSIONS_TABLE,
    CREATE_USER_ACTIVITY_TABLE,
    CREATE_ANALYTICS_EVENTS_TABLE
)

from .blog import (
    CREATE_BLOG_POSTS_TABLE,
    CREATE_BLOG_ANALYTICS_TABLE,
    CREATE_BLOG_ENGAGEMENT_TABLE,
    CREATE_BLOG_CATEGORIES_TABLE
)

from .fitness import (
    CREATE_FITNESS_PROGRAMS_TABLE,
    CREATE_FITNESS_EXERCISES_TABLE,
    CREATE_FITNESS_PROGRAM_EXERCISES_TABLE,
    CREATE_FITNESS_WORKOUTS_TABLE,
    CREATE_FITNESS_EXERCISE_LOGS_TABLE,
    CREATE_FITNESS_MEASUREMENTS_TABLE,
    CREATE_FITNESS_EQUIPMENT_TABLE,
    CREATE_FITNESS_BANDS_TABLE,
    CREATE_FITNESS_GOALS_TABLE,
    CREATE_FITNESS_NUTRITION_TABLE
)

from .media import (
    CREATE_MEDIA_MOVIES_TABLE,
    CREATE_MEDIA_GAMES_TABLE,
    CREATE_MEDIA_CONSUMPTION_TABLE,
    CREATE_MEDIA_PLATFORMS_TABLE,
    CREATE_MEDIA_ANALYTICS_TABLE
)