apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    helm.sh/chart: charts-0.1.0
    helm.sh/release-name: test-rel
    helm.sh/release-namespace: {{ .Values.namespace }}
    app.kubernetes.io/name: blog
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: blog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog
    spec:
      containers:
        - name: service-blog
          image: questmaster991/meetmyinterests:service-blog
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
          - name: MONGO_URI
            value: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@db-blog-service:27017"
      imagePullSecrets:
        - name: regcredentials